In [1]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectorized version:"+str(1000*(toc-tic))+"ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]  
toc=time.time()
print(c)
print("for loop version:"+str(1000*(toc-tic))+"ms")

249988.06036889163
Vectorized version:0.99945068359375ms
249988.0603688978
for loop version:500.69212913513184ms


In [12]:
# BROADCASING Example

In [13]:
import numpy as np

a=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])
print(a)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
cal=a.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [15]:
percentage=100*a/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [16]:
# PYTHON NUMPY VECTORS

In [18]:
a=np.random.randn(5)

In [20]:
print(a.shape)

(5,)


In [21]:
print(a.T)

[ 1.56532681 -1.42837883  0.50945551 -0.36606347  0.57977993]


In [22]:
print(np.dot(a,a.T))

5.220206258431532


In [25]:
a=np.random.randn(5,1)
print(a)

[[ 0.5542365 ]
 [ 0.36089456]
 [-0.17761391]
 [-0.14094077]
 [ 0.09909477]]


In [26]:
print(a.T)

[[ 0.5542365   0.36089456 -0.17761391 -0.14094077  0.09909477]]


In [27]:
print(np.dot(a,a.T))

[[ 0.3071781   0.20002094 -0.09844011 -0.07811452  0.05492194]
 [ 0.20002094  0.13024488 -0.06409989 -0.05086476  0.03576276]
 [-0.09844011 -0.06409989  0.0315467   0.02503304 -0.01760061]
 [-0.07811452 -0.05086476  0.02503304  0.0198643  -0.01396649]
 [ 0.05492194  0.03576276 -0.01760061 -0.01396649  0.00981977]]


In [28]:
a=np.random.randn(8,1)
print(a)

[[ 0.46858921]
 [-0.64710616]
 [-2.18025897]
 [ 0.07348835]
 [-3.09880048]
 [-0.53153631]
 [-0.02875443]
 [-1.84293073]]


In [34]:
a.reshape(2,2,2)

array([[[ 0.46858921, -0.64710616],
        [-2.18025897,  0.07348835]],

       [[-3.09880048, -0.53153631],
        [-0.02875443, -1.84293073]]])

In [37]:
a=np.random.randn(4,3)
b=np.random.randn(1,3)
c=a+b
c.shape

(4, 3)

In [38]:
a=np.random.randn(12288,150)
b=np.random.randn(150,45)
c=np.dot(a,b)
c.shape

(12288, 45)

In [41]:
# a.shape=(3,4)

# b.shape=(4,1)
a=np.random.randn(3,4)
b=np.random.randn(4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j]*b[j]

C:\Users\KIIT\AppData\Local\Temp\ipykernel_24424\1339001287.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  c[i][j] = a[i][j]*b[j]


In [43]:
c=np.dot(a,b)
c

array([[-2.08445345],
       [ 1.17372175],
       [-3.766387  ]])

In [56]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
c= a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [49]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)